### ISSUE TITLE
count_features.py error

### ISSUE THREAD

**Issue by c799** [molinfo-vienna/apo2ph4#1]
I tried to use a python script to calculate the potential pharmacophore characteristics of ligand,
But there is an error reported.
[error1.txt](https://github.com/aglanger/apo2ph4/files/10895443/error1.txt)
Boost.Python.ArgumentError: Python argument types in
DefaultPharmacophoreGenerator.init(DefaultPharmacophoreGenerator, bool)
did not match C++ signature:

I don't know how to solve this problem, I hope to get help

**Comment by seidelt** [comment]
Sorry for that! The apo2ph4 code is based on an older version of CDPKit and the Pharm.DefaultPharmacophoreGenerator constructor has changed in the meantime. Replacing 'pharm_gen = Pharm.DefaultPharmacophoreGenerator(True)' by 'pharm_gen = Pharm.DefaultPharmacophoreGenerator()' should fix the problem!

**Comment by seidelt** [comment]
count_features.py has now been adapted to work with the current CDPKit version

**Comment by c799** [comment]
Thank you for your response. After making the modifications to the script, all errors have been resolved and the new script runs successfully.
