### ISSUE TITLE
errors about knime

### ISSUE THREAD

**Issue by c799** [molinfo-vienna/apo2ph4#2]
I'm sorry to bother you again, but when I enter the knime command in apo2ph4_prepare_and_dock.sh, I get the following error, 
WARN 	 main Node	 Errors loading flow variables into node : Invalid path: /
WARN 	 main Node	 The LigandScout Knime Node Extensions are not licensed!
WARN 	 main Node	 The LigandScout Knime Node Extensions are not licensed!

 for ligandscout license, I refer to other people's solutions，but that doesn't help：
Please locate your KNIME installation folder. This folder should contain a file named knime.ini. In this file you can define startup parameters.

Add the following line to this file:

-Dcom.knime.licensedir=</path/to/directory/containing/serial/file>
The </path/to/directory/containing/serial/file> should be a path to a folder on your system that contains a file named serial. This serial file should contain your serial number and nothing else.

**Comment by seidelt** [comment]
The LigandScout Knime Node Extensions are commercial software and you need a license key to use them. I have talked to Prof. Thierry Langer (co-author of the paper and co-owner of InteLigand) and he will provide you with a free evaluation license. Please write an e-mail to support@inteligand.com with a subject like 'Request for a LS KNIME Extensions evaluation license to be able to use apo2ph4' and mention my name (Thomas Seidel) in the message body somewhere...

**Comment by c799** [comment]
Thank you for your help in resolving the issue with the LigandScout license. However, I have encountered a new problem and I am hoping that you could provide me with some guidance.

During the execution of the LigandScout KNIME extension, I encountered the following error message: 
 Mar 23, 2023 3:45:04 PM com.inteligand.ilib.pdb.x a
SEVERE: Alternative '-5944131901768659770' not matching core '-8215713561834636347'.
Mar 23, 2023 3:45:04 PM com.inteligand.ilib.pdb.x a
SEVERE: Alternative '71081847206633427' not matching core '5490675984603511878'.
Mar 23, 2023 3:45:04 PM com.inteligand.ilib.pdb.x a
SEVERE: Alternative '-8595303455525641851' not matching core '7469757997298185441'.
Mar 23, 2023 3:45:04 PM com.inteligand.ilib.pdb.x a
SEVERE: Alternative '4125246829410100706' not matching core '-3353753028943779712'.
Mar 23, 2023 3:45:04 PM com.inteligand.ilib.pdb.x a


I am not sure what caused this error or how to address it.

Could you please advise me on what steps I can take to resolve this issue? Any help or suggestions you can offer would be greatly appreciated.

Thank you for your time and assistance.

**Comment by seidelt** [comment]
This seems to be an error coming from the PDB reader node. Unfortunately, I cannot help you here because the error is located in the LigandScout  KNIME nodes. Please contact support@inteligand.com and ask them to have a look, maybe the problem is caused by a bug in the LigandScout code....
